import type { WordEntry } from './types'

/**
 * Kelime havuzu — 200+ kelime, 12 kategori.
 * Her kelime { word, hint, category, difficulty } formatında.
 * Zorluk: EASY (kısa/yaygın), MEDIUM (orta), HARD (uzun/özel).
 */
export const WORD_POOL: WordEntry[] = [
  // ─── Seyahat (17) ──────────────────────────────────────────────────────────
  { word: 'Pasaport', hint: 'Sınır geçiş belgesi', category: 'Seyahat', difficulty: 'EASY' },
  { word: 'Bavul', hint: 'Yolculuk çantası', category: 'Seyahat', difficulty: 'EASY' },
  { word: 'Otel', hint: 'Konaklama yeri', category: 'Seyahat', difficulty: 'EASY' },
  { word: 'Uçak', hint: 'Hava taşıtı', category: 'Seyahat', difficulty: 'EASY' },
  { word: 'Bilet', hint: 'Yolculuk kartı', category: 'Seyahat', difficulty: 'EASY' },
  { word: 'Harita', hint: 'Yol gösteren çizim', category: 'Seyahat', difficulty: 'EASY' },
  { word: 'Turist', hint: 'Gezgin kişi', category: 'Seyahat', difficulty: 'EASY' },
  { word: 'Valiz', hint: 'Sert seyahat çantası', category: 'Seyahat', difficulty: 'EASY' },
  { word: 'Rehber', hint: 'Yol gösteren kişi veya kitap', category: 'Seyahat', difficulty: 'MEDIUM' },
  { word: 'Terminal', hint: 'Havalimanı bölümü', category: 'Seyahat', difficulty: 'MEDIUM' },
  { word: 'Vize', hint: 'Giriş izni', category: 'Seyahat', difficulty: 'MEDIUM' },
  { word: 'Hostes', hint: 'Uçak görevlisi', category: 'Seyahat', difficulty: 'MEDIUM' },
  { word: 'Pansiyon', hint: 'Küçük konaklama yeri', category: 'Seyahat', difficulty: 'MEDIUM' },
  { word: 'Transfer', hint: 'Yolcu taşıma hizmeti', category: 'Seyahat', difficulty: 'MEDIUM' },
  { word: 'Pasaport kontrol', hint: 'Sınır geçiş noktası', category: 'Seyahat', difficulty: 'HARD' },
  { word: 'Bekleme salonu', hint: 'Uçuş öncesi dinlenme yeri', category: 'Seyahat', difficulty: 'HARD' },
  { word: 'Gümrük', hint: 'Sınır mal kontrolü', category: 'Seyahat', difficulty: 'HARD' },

  // ─── Kamp (17) ─────────────────────────────────────────────────────────────
  { word: 'Çadır', hint: 'Açık hava barınağı', category: 'Kamp', difficulty: 'EASY' },
  { word: 'Kamp ateşi', hint: 'Ateş yakılan yer', category: 'Kamp', difficulty: 'EASY' },
  { word: 'Uyku tulumu', hint: 'Sıcak tutan kılıf', category: 'Kamp', difficulty: 'EASY' },
  { word: 'Matara', hint: 'Su şişesi', category: 'Kamp', difficulty: 'EASY' },
  { word: 'Fener', hint: 'El ışığı', category: 'Kamp', difficulty: 'EASY' },
  { word: 'Sırt çantası', hint: 'Sırta takılan çanta', category: 'Kamp', difficulty: 'EASY' },
  { word: 'Pusula', hint: 'Yön bulma aracı', category: 'Kamp', difficulty: 'EASY' },
  { word: 'Çakmak', hint: 'Ateş yakma aracı', category: 'Kamp', difficulty: 'EASY' },
  { word: 'İp', hint: 'Bağlama aracı', category: 'Kamp', difficulty: 'EASY' },
  { word: 'Kamp stove', hint: 'Taşınabilir ocak', category: 'Kamp', difficulty: 'MEDIUM' },
  { word: 'Moskit ağı', hint: 'Böcek koruması', category: 'Kamp', difficulty: 'MEDIUM' },
  { word: 'Kazık', hint: 'Çadır sabitleyici', category: 'Kamp', difficulty: 'MEDIUM' },
  { word: 'Termos', hint: 'Sıcak tutan kap', category: 'Kamp', difficulty: 'MEDIUM' },
  { word: 'Balta', hint: 'Odun kesme aracı', category: 'Kamp', difficulty: 'MEDIUM' },
  { word: 'Hidrasyon paketi', hint: 'Sırtta su deposu', category: 'Kamp', difficulty: 'HARD' },
  { word: 'Ateş başlatıcı', hint: 'Magnesyum çubuğu', category: 'Kamp', difficulty: 'HARD' },
  { word: 'Gece görüşü', hint: 'Karanlıkta gören cihaz', category: 'Kamp', difficulty: 'HARD' },

  // ─── Müzik (17) ────────────────────────────────────────────────────────────
  { word: 'Gitar', hint: 'Telli çalgı', category: 'Müzik', difficulty: 'EASY' },
  { word: 'Piyano', hint: 'Tuşlu çalgı', category: 'Müzik', difficulty: 'EASY' },
  { word: 'Davul', hint: 'Vurmalı çalgı', category: 'Müzik', difficulty: 'EASY' },
  { word: 'Şarkı', hint: 'Sözlü müzik', category: 'Müzik', difficulty: 'EASY' },
  { word: 'Nota', hint: 'Müzik sembolü', category: 'Müzik', difficulty: 'EASY' },
  { word: 'Mikrofon', hint: 'Ses yakalama aracı', category: 'Müzik', difficulty: 'EASY' },
  { word: 'Konser', hint: 'Canlı müzik etkinliği', category: 'Müzik', difficulty: 'EASY' },
  { word: 'Ritim', hint: 'Müzik vuruşu', category: 'Müzik', difficulty: 'EASY' },
  { word: 'Keman', hint: 'Yaylı çalgı', category: 'Müzik', difficulty: 'MEDIUM' },
  { word: 'Flüt', hint: 'Üflemeli çalgı', category: 'Müzik', difficulty: 'MEDIUM' },
  { word: 'Orkestra', hint: 'Büyük müzik topluluğu', category: 'Müzik', difficulty: 'MEDIUM' },
  { word: 'Melodi', hint: 'Müzik dizisi', category: 'Müzik', difficulty: 'MEDIUM' },
  { word: 'Akor', hint: 'Birlikte çalınan notalar', category: 'Müzik', difficulty: 'MEDIUM' },
  { word: 'Saksafon', hint: 'Üflemeli çalgı', category: 'Müzik', difficulty: 'MEDIUM' },
  { word: 'Senfoni', hint: 'Büyük orkestra eseri', category: 'Müzik', difficulty: 'HARD' },
  { word: 'Metronom', hint: 'Ritim cihazı', category: 'Müzik', difficulty: 'HARD' },
  { word: 'Armonika', hint: 'Ağız çalgısı', category: 'Müzik', difficulty: 'HARD' },

  // ─── Yiyecek (17) ──────────────────────────────────────────────────────────
  { word: 'Pizza', hint: 'İtalyan yemeği', category: 'Yiyecek', difficulty: 'EASY' },
  { word: 'Hamburger', hint: 'Etli sandviç', category: 'Yiyecek', difficulty: 'EASY' },
  { word: 'Pasta', hint: 'Tatlı', category: 'Yiyecek', difficulty: 'EASY' },
  { word: 'Salata', hint: 'Sebze yemeği', category: 'Yiyecek', difficulty: 'EASY' },
  { word: 'Çorba', hint: 'Sıcak yemek', category: 'Yiyecek', difficulty: 'EASY' },
  { word: 'Pilav', hint: 'Pirinç yemeği', category: 'Yiyecek', difficulty: 'EASY' },
  { word: 'Kebap', hint: 'Et yemeği', category: 'Yiyecek', difficulty: 'EASY' },
  { word: 'Sandviç', hint: 'İki ekmek arası', category: 'Yiyecek', difficulty: 'EASY' },
  { word: 'Lahmacun', hint: 'İnce hamurlu et yemeği', category: 'Yiyecek', difficulty: 'MEDIUM' },
  { word: 'Mantı', hint: 'Küçük hamur yemeği', category: 'Yiyecek', difficulty: 'MEDIUM' },
  { word: 'Baklava', hint: 'Şerbetli tatlı', category: 'Yiyecek', difficulty: 'MEDIUM' },
  { word: 'Döner', hint: 'Dönen et yemeği', category: 'Yiyecek', difficulty: 'MEDIUM' },
  { word: 'Ravioli', hint: 'İtalyan hamur yemeği', category: 'Yiyecek', difficulty: 'MEDIUM' },
  { word: 'Sushi', hint: 'Japon pirinç yemeği', category: 'Yiyecek', difficulty: 'MEDIUM' },
  { word: 'Paella', hint: 'İspanyol pilavı', category: 'Yiyecek', difficulty: 'HARD' },
  { word: 'Tiramisu', hint: 'İtalyan tatlısı', category: 'Yiyecek', difficulty: 'HARD' },
  { word: 'Gnocchi', hint: 'İtalyan patates hamuru', category: 'Yiyecek', difficulty: 'HARD' },

  // ─── Spor (17) ─────────────────────────────────────────────────────────────
  { word: 'Futbol', hint: 'Top oyunu', category: 'Spor', difficulty: 'EASY' },
  { word: 'Basketbol', hint: 'Potaya top atma', category: 'Spor', difficulty: 'EASY' },
  { word: 'Tenis', hint: 'Raket oyunu', category: 'Spor', difficulty: 'EASY' },
  { word: 'Yüzme', hint: 'Su sporu', category: 'Spor', difficulty: 'EASY' },
  { word: 'Koşu', hint: 'Hızlı yürüyüş', category: 'Spor', difficulty: 'EASY' },
  { word: 'Bisiklet', hint: 'İki tekerlekli', category: 'Spor', difficulty: 'EASY' },
  { word: 'Voleybol', hint: 'File üzerinden top', category: 'Spor', difficulty: 'EASY' },
  { word: 'Gol', hint: 'Sayı kazanma', category: 'Spor', difficulty: 'EASY' },
  { word: 'Boks', hint: 'Eldivenli dövüş', category: 'Spor', difficulty: 'MEDIUM' },
  { word: 'Karate', hint: 'Japon dövüş sanatı', category: 'Spor', difficulty: 'MEDIUM' },
  { word: 'Yelken', hint: 'Rüzgar sporu', category: 'Spor', difficulty: 'MEDIUM' },
  { word: 'Eskrim', hint: 'Kılıç sporu', category: 'Spor', difficulty: 'MEDIUM' },
  { word: 'Jimnastik', hint: 'Esneklik sporu', category: 'Spor', difficulty: 'MEDIUM' },
  { word: 'Triatlon', hint: 'Üçlü spor', category: 'Spor', difficulty: 'MEDIUM' },
  { word: 'Polo', hint: 'Atlı top oyunu', category: 'Spor', difficulty: 'HARD' },
  { word: 'Kürek', hint: 'Su sporu', category: 'Spor', difficulty: 'HARD' },
  { word: 'Bobsleigh', hint: 'Buz kızak sporu', category: 'Spor', difficulty: 'HARD' },

  // ─── Doğa (17) ─────────────────────────────────────────────────────────────
  { word: 'Ağaç', hint: 'Bitki', category: 'Doğa', difficulty: 'EASY' },
  { word: 'Çiçek', hint: 'Renkli bitki', category: 'Doğa', difficulty: 'EASY' },
  { word: 'Dağ', hint: 'Yüksek yer', category: 'Doğa', difficulty: 'EASY' },
  { word: 'Nehir', hint: 'Akarsu', category: 'Doğa', difficulty: 'EASY' },
  { word: 'Göl', hint: 'Su birikintisi', category: 'Doğa', difficulty: 'EASY' },
  { word: 'Orman', hint: 'Ağaçlık alan', category: 'Doğa', difficulty: 'EASY' },
  { word: 'Güneş', hint: 'Yıldız', category: 'Doğa', difficulty: 'EASY' },
  { word: 'Yağmur', hint: 'Su damlaları', category: 'Doğa', difficulty: 'EASY' },
  { word: 'Şelale', hint: 'Dökülen su', category: 'Doğa', difficulty: 'MEDIUM' },
  { word: 'Volkan', hint: 'Ateş dağı', category: 'Doğa', difficulty: 'MEDIUM' },
  { word: 'Buzul', hint: 'Buz kütlesi', category: 'Doğa', difficulty: 'MEDIUM' },
  { word: 'Mağara', hint: 'Yer altı boşluğu', category: 'Doğa', difficulty: 'MEDIUM' },
  { word: 'Çöl', hint: 'Kum alan', category: 'Doğa', difficulty: 'MEDIUM' },
  { word: 'Okyanus', hint: 'Büyük su', category: 'Doğa', difficulty: 'MEDIUM' },
  { word: 'Kanyon', hint: 'Dar vadi', category: 'Doğa', difficulty: 'HARD' },
  { word: 'Gezegen', hint: 'Gök cismi', category: 'Doğa', difficulty: 'HARD' },
  { word: 'Kuasar', hint: 'Parlak gök cismi', category: 'Doğa', difficulty: 'HARD' },

  // ─── Meslek (17) ───────────────────────────────────────────────────────────
  { word: 'Doktor', hint: 'Sağlıkçı', category: 'Meslek', difficulty: 'EASY' },
  { word: 'Öğretmen', hint: 'Eğitmen', category: 'Meslek', difficulty: 'EASY' },
  { word: 'Polis', hint: 'Güvenlikçi', category: 'Meslek', difficulty: 'EASY' },
  { word: 'Aşçı', hint: 'Yemek yapan', category: 'Meslek', difficulty: 'EASY' },
  { word: 'Şoför', hint: 'Araç kullanan', category: 'Meslek', difficulty: 'EASY' },
  { word: 'Berber', hint: 'Saç kesen', category: 'Meslek', difficulty: 'EASY' },
  { word: 'Mühendis', hint: 'Tasarımcı', category: 'Meslek', difficulty: 'EASY' },
  { word: 'Tarihçi', hint: 'Geçmişi inceleyen', category: 'Meslek', difficulty: 'EASY' },
  { word: 'Veteriner', hint: 'Hayvan doktoru', category: 'Meslek', difficulty: 'MEDIUM' },
  { word: 'Pilot', hint: 'Uçak sürücü', category: 'Meslek', difficulty: 'MEDIUM' },
  { word: 'Avukat', hint: 'Hukukçu', category: 'Meslek', difficulty: 'MEDIUM' },
  { word: 'Eczacı', hint: 'İlaç satan', category: 'Meslek', difficulty: 'MEDIUM' },
  { word: 'Mimar', hint: 'Bina tasarımcısı', category: 'Meslek', difficulty: 'MEDIUM' },
  { word: 'Arkeolog', hint: 'Kazı bilimci', category: 'Meslek', difficulty: 'MEDIUM' },
  { word: 'Borsacı', hint: 'Finansçı', category: 'Meslek', difficulty: 'HARD' },
  { word: 'Diplomat', hint: 'Devlet temsilcisi', category: 'Meslek', difficulty: 'HARD' },
  { word: 'Küratör', hint: 'Sergi yöneticisi', category: 'Meslek', difficulty: 'HARD' },

  // ─── Ev Eşyaları (17) ──────────────────────────────────────────────────────
  { word: 'Masa', hint: 'Üst yüzey', category: 'Ev Eşyaları', difficulty: 'EASY' },
  { word: 'Sandalye', hint: 'Oturma aracı', category: 'Ev Eşyaları', difficulty: 'EASY' },
  { word: 'Yatak', hint: 'Uyku yeri', category: 'Ev Eşyaları', difficulty: 'EASY' },
  { word: 'Dolap', hint: 'Saklama yeri', category: 'Ev Eşyaları', difficulty: 'EASY' },
  { word: 'Lamba', hint: 'Işık kaynağı', category: 'Ev Eşyaları', difficulty: 'EASY' },
  { word: 'Halı', hint: 'Yer örtüsü', category: 'Ev Eşyaları', difficulty: 'EASY' },
  { word: 'Ayna', hint: 'Yansıtıcı', category: 'Ev Eşyaları', difficulty: 'EASY' },
  { word: 'Bardak', hint: 'İçecek kabı', category: 'Ev Eşyaları', difficulty: 'EASY' },
  { word: 'Vazo', hint: 'Çiçek kabı', category: 'Ev Eşyaları', difficulty: 'MEDIUM' },
  { word: 'Abajur', hint: 'Süreli ışık', category: 'Ev Eşyaları', difficulty: 'MEDIUM' },
  { word: 'Mutfak robotu', hint: 'Mutfak aleti', category: 'Ev Eşyaları', difficulty: 'MEDIUM' },
  { word: 'Ütü', hint: 'Kıyafet düzeltici', category: 'Ev Eşyaları', difficulty: 'MEDIUM' },
  { word: 'Vakum', hint: 'Temizlik aleti', category: 'Ev Eşyaları', difficulty: 'MEDIUM' },
  { word: 'Şifonyer', hint: 'Çekmeceli dolap', category: 'Ev Eşyaları', difficulty: 'MEDIUM' },
  { word: 'Puf', hint: 'Oturma yastığı', category: 'Ev Eşyaları', difficulty: 'HARD' },
  { word: 'Konsol', hint: 'Dar masa', category: 'Ev Eşyaları', difficulty: 'HARD' },
  { word: 'Büfe', hint: 'Yiyecek dolabı', category: 'Ev Eşyaları', difficulty: 'HARD' },

  // ─── Giyim (17) ────────────────────────────────────────────────────────────
  { word: 'Tişört', hint: 'Üst giyim', category: 'Giyim', difficulty: 'EASY' },
  { word: 'Pantolon', hint: 'Alt giyim', category: 'Giyim', difficulty: 'EASY' },
  { word: 'Ayakkabı', hint: 'Ayak giyim', category: 'Giyim', difficulty: 'EASY' },
  { word: 'Şapka', hint: 'Baş giyim', category: 'Giyim', difficulty: 'EASY' },
  { word: 'Çorap', hint: 'Ayak koruması', category: 'Giyim', difficulty: 'EASY' },
  { word: 'Eldiven', hint: 'El koruması', category: 'Giyim', difficulty: 'EASY' },
  { word: 'Atkı', hint: 'Boyna sarılan', category: 'Giyim', difficulty: 'EASY' },
  { word: 'Ceket', hint: 'Üst giyim', category: 'Giyim', difficulty: 'EASY' },
  { word: 'Yelek', hint: 'Sırt giyim', category: 'Giyim', difficulty: 'MEDIUM' },
  { word: 'Kravat', hint: 'Boyna bağlanan', category: 'Giyim', difficulty: 'MEDIUM' },
  { word: 'Pijama', hint: 'Uyku giyim', category: 'Giyim', difficulty: 'MEDIUM' },
  { word: 'Şort', hint: 'Kısa alt giyim', category: 'Giyim', difficulty: 'MEDIUM' },
  { word: 'Bluz', hint: 'Kadın üst giyim', category: 'Giyim', difficulty: 'MEDIUM' },
  { word: 'Palto', hint: 'Kış üst giyim', category: 'Giyim', difficulty: 'MEDIUM' },
  { word: 'Yelek takım', hint: 'Takım giyim', category: 'Giyim', difficulty: 'HARD' },
  { word: 'Kuşak', hint: 'Bel bağlayıcı', category: 'Giyim', difficulty: 'HARD' },
  { word: 'Şalvar', hint: 'Geleneksel alt giyim', category: 'Giyim', difficulty: 'HARD' },

  // ─── Teknoloji (17) ────────────────────────────────────────────────────────
  { word: 'Telefon', hint: 'İletişim aracı', category: 'Teknoloji', difficulty: 'EASY' },
  { word: 'Bilgisayar', hint: 'Hesaplama cihazı', category: 'Teknoloji', difficulty: 'EASY' },
  { word: 'Tablet', hint: 'Dokunmatik cihaz', category: 'Teknoloji', difficulty: 'EASY' },
  { word: 'Kulaklık', hint: 'Ses cihazı', category: 'Teknoloji', difficulty: 'EASY' },
  { word: 'Kamera', hint: 'Fotoğraf cihazı', category: 'Teknoloji', difficulty: 'EASY' },
  { word: 'Şarj', hint: 'Elektrik dolumu', category: 'Teknoloji', difficulty: 'EASY' },
  { word: 'Ekran', hint: 'Görüntü yüzeyi', category: 'Teknoloji', difficulty: 'EASY' },
  { word: 'Klavye', hint: 'Yazı aracı', category: 'Teknoloji', difficulty: 'EASY' },
  { word: 'Yazıcı', hint: 'Çıktı cihazı', category: 'Teknoloji', difficulty: 'MEDIUM' },
  { word: 'Tarayıcı', hint: 'Dijitalbeleştirici', category: 'Teknoloji', difficulty: 'MEDIUM' },
  { word: 'Router', hint: 'Ağ cihazı', category: 'Teknoloji', difficulty: 'MEDIUM' },
  { word: 'Drone', hint: 'Uzaktan kumandalı hava aracı', category: 'Teknoloji', difficulty: 'MEDIUM' },
  { word: 'Akıllı saat', hint: 'Bilek cihazı', category: 'Teknoloji', difficulty: 'MEDIUM' },
  { word: 'Bluetooth', hint: 'Kablosuz bağlantı', category: 'Teknoloji', difficulty: 'MEDIUM' },
  { word: 'Blockchain', hint: 'Zincir teknoloji', category: 'Teknoloji', difficulty: 'HARD' },
  { word: 'Kuantum bilgisayar', hint: 'Gelişmiş hesap cihazı', category: 'Teknoloji', difficulty: 'HARD' },
  { word: 'NFC', hint: 'Yakın alan iletişim', category: 'Teknoloji', difficulty: 'HARD' },

  // ─── Hayvanlar (17) ────────────────────────────────────────────────────────
  { word: 'Kedi', hint: 'Ev hayvanı', category: 'Hayvanlar', difficulty: 'EASY' },
  { word: 'Köpek', hint: 'Sadık dost', category: 'Hayvanlar', difficulty: 'EASY' },
  { word: 'Kuş', hint: 'Uçan hayvan', category: 'Hayvanlar', difficulty: 'EASY' },
  { word: 'Balık', hint: 'Su hayvanı', category: 'Hayvanlar', difficulty: 'EASY' },
  { word: 'At', hint: 'Sürüngen hayvan', category: 'Hayvanlar', difficulty: 'EASY' },
  { word: 'İnek', hint: 'Süt hayvanı', category: 'Hayvanlar', difficulty: 'EASY' },
  { word: 'Tavşan', hint: 'Zıplayan hayvan', category: 'Hayvanlar', difficulty: 'EASY' },
  { word: 'Tavuk', hint: 'Kanatlı hayvan', category: 'Hayvanlar', difficulty: 'EASY' },
  { word: 'Kanguru', hint: 'Keseli hayvan', category: 'Hayvanlar', difficulty: 'MEDIUM' },
  { word: 'Penguen', hint: 'Kutup kuşu', category: 'Hayvanlar', difficulty: 'MEDIUM' },
  { word: 'Zürafa', hint: 'Uzun boyunlu', category: 'Hayvanlar', difficulty: 'MEDIUM' },
  { word: 'Yunus', hint: 'Akıllı deniz hayvanı', category: 'Hayvanlar', difficulty: 'MEDIUM' },
  { word: 'Sincap', hint: 'Ağaç hayvanı', category: 'Hayvanlar', difficulty: 'MEDIUM' },
  { word: 'Vaşak', hint: 'Yırtıcı kedi', category: 'Hayvanlar', difficulty: 'MEDIUM' },
  { word: 'Karınca', hint: 'Sosyal böcek', category: 'Hayvanlar', difficulty: 'HARD' },
  { word: 'Kaplumbağa', hint: 'Kabuklu hayvan', category: 'Hayvanlar', difficulty: 'HARD' },
  { word: 'Ahtapot', hint: 'Sekiz kollu deniz hayvanı', category: 'Hayvanlar', difficulty: 'HARD' },

  // ─── Taşıtlar (17) ─────────────────────────────────────────────────────────
  { word: 'Araba', hint: 'Kara taşıtı', category: 'Taşıtlar', difficulty: 'EASY' },
  { word: 'Otobüs', hint: 'Toplu taşıma', category: 'Taşıtlar', difficulty: 'EASY' },
  { word: 'Tren', hint: 'Ray taşıtı', category: 'Taşıtlar', difficulty: 'EASY' },
  { word: 'Gemi', hint: 'Su taşıtı', category: 'Taşıtlar', difficulty: 'EASY' },
  { word: 'Bisiklet', hint: 'İki tekerlekli', category: 'Taşıtlar', difficulty: 'EASY' },
  { word: 'Motosiklet', hint: 'İki tekerlekli motorlu', category: 'Taşıtlar', difficulty: 'EASY' },
  { word: 'Helikopter', hint: 'Dönen kanatlı', category: 'Taşıtlar', difficulty: 'EASY' },
  { word: 'Metro', hint: 'Yer altı taşıtı', category: 'Taşıtlar', difficulty: 'EASY' },
  { word: 'Tramvay', hint: 'Şehir ray taşıtı', category: 'Taşıtlar', difficulty: 'MEDIUM' },
  { word: 'Tekne', hint: 'Küçük su taşıtı', category: 'Taşıtlar', difficulty: 'MEDIUM' },
  { word: 'Kamyon', hint: 'Yük taşıtı', category: 'Taşıtlar', difficulty: 'MEDIUM' },
  { word: 'Minibüs', hint: 'Küçük taşıt', category: 'Taşıtlar', difficulty: 'MEDIUM' },
  { word: 'Forklift', hint: 'Yük kaldırma aracı', category: 'Taşıtlar', difficulty: 'MEDIUM' },
  { word: 'Yat', hint: 'Lüks deniz taşıtı', category: 'Taşıtlar', difficulty: 'MEDIUM' },
  { word: 'Hoverkraft', hint: 'Hava yastıklı taşıt', category: 'Taşıtlar', difficulty: 'HARD' },
  { word: 'Denizaltı', hint: 'Su altı taşıtı', category: 'Taşıtlar', difficulty: 'HARD' },
  { word: 'Balon', hint: 'Hava taşıtı', category: 'Taşıtlar', difficulty: 'HARD' },
]

/** Tüm kategorilerin listesi. */
export const CATEGORIES: string[] = Array.from(new Set(WORD_POOL.map((w) => w.category)))

/** Bir kategorideki kelime sayısı. */
export function categoryCount(category: string): number {
  return WORD_POOL.filter((w) => w.category === category).length
}
